# Generated by Django 5.0.2 on 2024-02-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
