# Generated by Django 5.0.2 on 2024-03-03 16:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0003_security_price_security_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='volume',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), size=None),
        ),
    ]
