# Generated by Django 5.0.2 on 2024-05-22 15:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0005_alter_security_options_security_users_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='security',
            old_name='price',
            new_name='price_all',
        ),
        migrations.AddField(
            model_name='security',
            name='trade_dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), default=None, size=None),
            preserve_default=False,
        ),
    ]
