# Generated by Django 5.0.2 on 2024-03-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovingAverages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('period', models.PositiveIntegerField()),
                ('linestyle', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=7)),
                ('lineType', models.CharField(max_length=3)),
            ],
        ),
    ]
